#!/bin/bash
cd ~/LubuntuInsBasic/files

sudo mv apt ~/
sudo mv flatpak ~/
sudo mv pip ~/
sudo mv snapd ~/
sudo mv scrcpy_scrcpy2 /usr/share/applications/scrcpy_scrcpy2.desktop
sudo mv sndcpy.d /usr/share/applications/sndcpy.desktop
sudo mv whatsappFirefox /usr/share/applications/whatsappFirefox.desktop
sudo mv screenC /usr/share/applications/screenC.desktop
sudo mv rcw /usr/share/applications/rcw.desktop
sudo mv left.png below.png above.png right.jpg wallpaper2.jpg /usr/share/lxqt/themes/dark/
sudo mv bashrc ~/.bashrc
sudo mv bash_history ~/.bash_history
sudo mv ejmForN ~/.ejmForN
sudo mv ejmFor ~/.ejmFor

sudo mkdir /opt/ /opt/cscreen /opt/cxtermux /opt/EliFecha /opt/envtermux /opt/FlightGear /opt/genymobile /opt/InSnap /opt/instalar /opt/PianoBooster /opt/RebW /opt/sndcpy /opt/VmPiano /opt/updGo /opt/TextSnatcher

sudo apt update > /dev/null 2>&1
dpkg -s snap &> /dev/null
if [ $? -ne 0 ]
   then
      echo "snap no está instalado, instalando..."
      sudo apt-get install snap -y > /dev/null 2>&1
fi

dpkg -s snapd &> /dev/null
if [ $? -ne 0 ]
   then
      echo "snapd no está instalado, instalando..."
      sudo apt-get install snapd -y > /dev/null 2>&1
fi

dpkg -s python3 &> /dev/null
if [ $? -ne 0 ]
   then
      echo "python3 no está instalado, instalando..."
      sudo apt-get install python3 -y > /dev/null 2>&1
fi

dpkg -s python3-pip &> /dev/null
if [ $? -ne 0 ]
   then
      echo "python3-pip no está instalado, instalando..."
      sudo apt-get install python3-pip -y > /dev/null 2>&1
fi

sudo apt install scrcpy -y > /dev/null 2>&1
sudo apt update > /dev/null 2>&1
sudo /etc/init.d/cron start
sudo /etc/init.d/cron restart

oldIFS=$IFS     # conserva el separador de campo
IFS=$'\n'     # nuevo separador de campo, el caracter fin de línea
for line in $(cat $HOME/apt)
do
  dpkg -l | grep $line
  if [ $? -ne 0 ]
   then
   sudo apt install $line -y   
  fi
done
IFS=$old_IFS
oldIFS=$IFS
IFS=$'\n'
for line2 in $(cat $HOME/snapd)
do
  dpkg -l | grep $line2
  if [ $? -ne 0 ]
   then
   sudo snap install $line2   
  fi
done
IFS=$old_IFS
oldIFS=$IFS
IFS=$'\n'
for line3 in $(cat $HOME/flatpak)
do
  dpkg -l | grep $line3
  if [ $? -ne 0 ]
   then
   sudo flatpak install $line3 -y   
  fi
done
IFS=$old_IFS
oldIFS=$IFS
IFS=$'\n'
for line4 in $(cat $HOME/pip)
do
  dpkg -l | grep $line4
  if [ $? -ne 0 ]
   then
   pip install $line4 
  fi
done
IFS=$old_IFS 

sudo apt install software-properties-common apt-transport-https wget
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt update
sudo apt install code



sudo apt update
sudo apt upgrade -y

wget -i https://download.flightgear.org/builds/2020.3/FlightGear-2020.3.13-x86_64.AppImage
wget -np https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1-linux_x64.bin
wget https://github.com/pianobooster/PianoBooster/releases/download/v1.0.0/PianoBooster-1.0.0-x86_64.AppImage
wget -np https://sourceforge.net/projects/vmpk/files/vmpk/0.8.7/vmpk-0.8.7-linux-x86_64.AppImage/download -O vmpkPiano.AppImage
wget -np https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
wget -q https://raw.githubusercontent.com/MartinCiro/SenaProyects/gh-pages/docs/media/sgv/TextSnatcher.svg


sudo mv screenP /opt/cscreen/screenP
sudo mv conectar /opt/cxtermux/
sudo mv Eliminar /opt/EliFecha/
sudo mv EnviarSsh /opt/envtermux/
sudo mv FlightGear* /opt/FlightGear/
sudo mv InSnap /opt/InSnap/
sudo mv install /opt/instalar/
sudo mv PianoBooster* /opt/PianoBooster/
sudo mv RebootW* /opt/RebW/
sudo mv mv completoSnd copia2 ejecucion prototipox snd* /opt/sndcpy/
sudo mv vmpkPiano* /opt/VmPiano/
sudo mv actGo /opt/updGo/
sudo mv TextSnatcher.svg /opt/TextSnatcher

sudo add-apt-repository ppa:mkusb/ppa
sudo apt update
sudo apt install mkusb mkusb-nox usb-pack-efi -y

sudo chmod 777 google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo bash genymotion-3.2.1-linux_x64.bin -y
wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz &> /dev/null
tar -xvzf ngrok-v3-stable-linux-amd64.tgz &> /dev/null
chmod 777 ngrok &> /dev/null
sudo mv ngrok /usr/bin/ngrok
echo "Ingrese el token de ngrok"
read ng
ngrok config add-authtoken $ng

ssh-keygen -t rsa -b 4096 -C "martinciro11@gmail.com"
echo "Por favor copie el contenido del rsa y peguelo en la pagina de git"
cat ~/.ssh/id_rsa
echo "Preciona una tecla para continuar..."
read ng
cd ~/


rm -fr ~/LubuntuInsBasic
rm -fr ~/apt 
rm -fr ~/flatpak
rm -fr ~/pip
rm -fr ~/snapd
