#!/bin/bash
cd ~/files
wget -i https://download.flightgear.org/builds/2020.3/FlightGear-2020.3.13-x86_64.AppImage
wget -np https://dl.genymotion.com/releases/genymotion-3.2.1/genymotion-3.2.1-linux_x64.bin
wget https://github.com/pianobooster/PianoBooster/releases/download/v1.0.0/PianoBooster-1.0.0-x86_64.AppImage
wget -np https://sourceforge.net/projects/vmpk/files/vmpk/0.8.7/vmpk-0.8.7-linux-x86_64.AppImage/download -O vmpkPiano.AppImage

sudo mv apt ~/
sudo mv flatpak ~/
sudo mv pip ~/
sudo mv snapd ~/
sudo mv scrcpy_scrcpy2 /usr/share/applications/scrcpy_scrcpy2.desktop
sudo mv sndcpy.d /usr/share/applications/sndcpy.desktop
sudo mv whatsappFirefox /usr/share/applications/whatsappFirefox.desktop
sudo mv screenC /usr/share/applications/screenC.desktop
sudo mv rcw /usr/share/applications/rcw.desktop
sudo mv left.png below.png above.png right.jpg wallpaper2.jpg /usr/share/lxqt/themes/dark/

mkdir /opt/
mkdir /opt/cscreen
mkdir /opt/cxtermux
mkdir /opt/EliFecha
mkdir /opt/envtermux
mkdir /opt/FlightGear
mkdir /opt/genymobile
mkdir /opt/InSnap
mkdir /opt/instalar
mkdir /opt/PianoBooster
mkdir /opt/RebW
mkdir /opt/sndcpy
mkdir /opt/VmPiano

sudo mv screenP /opt/cscreen/screenP
sudo sudo mv conectar /opt/cxtermux/
sudo sudo mv Eliminar /opt/EliFecha/
sudo sudo mv EnviarSsh /opt/envtermux/
sudo sudo mv FlightGear* /opt/FlightGear/
sudo sudo mv InSnap /opt/InSnap/
sudo sudo mv install /opt/instalar/
sudo sudo mv PianoBooster* /opt/PianoBooster/
sudo sudo mv RebootW* /opt/RebW/
sudo sudo mv mv completoSnd copia2 ejecucion prototipox snd* /opt/sndcpy/
sudo sudo mv vmpkPiano* /opt/VmPiano/

sudo apt update > /dev/null 2>&1
psn="snap"
psnd="snapd"
ppp="python3"
ppip="python3-pip"
dpkg -s $psn &> /dev/null
if [ $? -ne 0 ]
   then
      echo "${psn} no está instalado, instalando..."
      sudo apt-get install $psn -y > /dev/null 2>&1
fi

dpkg -s $psnd &> /dev/null
if [ $? -ne 0 ]
   then
      echo "${psnd} no está instalado, instalando..."
      sudo apt-get install $psnd -y > /dev/null 2>&1
fi

dpkg -s $ppp &> /dev/null
if [ $? -ne 0 ]
   then
      echo "${ppp} no está instalado, instalando..."
      sudo apt-get install $ppp -y > /dev/null 2>&1
fi

dpkg -s $ppip &> /dev/null
if [ $? -ne 0 ]
   then
      echo "${ppip} no está instalado, instalando..."
      sudo apt-get install $ppip -y > /dev/null 2>&1
fi

sudo apt update > /dev/null 2>&1
exit
oldIFS=$IFS     # conserva el separador de campo
IFS=$'\n'     # nuevo separador de campo, el caracter fin de línea
for line in $(cat $HOME/apt)
do
  dpkg -l | grep $line
  if [ $? -ne 0 ]
   then
   sudo apt install $line -y   
  fi
done
for line2 in $(cat $HOME/snap.)
do
  dpkg -l | grep $line2
  if [ $? -ne 0 ]
   then
   sudo snap install $line2   
  fi
done
for line3 in $(cat $HOME/flatpak)
do
  dpkg -l | grep $line3
  if [ $? -ne 0 ]
   then
   sudo flatpak install $line3 -y   
  fi
for line4 in $(cat $HOME/pip)
do
  dpkg -l | grep $line4
  if [ $? -ne 0 ]
   then
   pip install $line4 
  fi
done
IFS=$old_IFS     # restablece el separador de campo predeterminado
sudo apt update
sudo apt upgrade -y
sudo bash genymotion-3.2.1-linux_x64.bin -y
