#!/bin/bash
mv -f /storage/emulated/0/Alarms/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Alarms/
cp /storage/emulated/0/Alarms/
mv -f /storage/emulated/0/Cap/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Cap/
mv -f /storage/emulated/0/Documents/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Documents/
mv -f /storage/emulated/0/Fonts/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Fonts/
mv -f /storage/emulated/0/MiVideoDownload/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/MiVideoDownload/
mv -f /storage/emulated/0/Music/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Music/
mv -f /storage/emulated/0/Pictures/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Pictures/
mv -f /storage/emulated/0/WhatsApp/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/WhatsApp/
mv -f /storage/emulated/0/backups/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/backups/
mv -f /storage/emulated/0/DCIM/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/DCIM/
mv -f /storage/emulated/0/Download/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Download/
mv -f /storage/emulated/0/MIUI/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/MIUI/
mv -f /storage/emulated/0/Movies/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Movies/
mv -f /storage/emulated/0/PicsArt/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/PicsArt/
mv -f /storage/emulated/0/Recordings/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/Recordings/
mv -f /storage/emulated/0/txtpad/ /storage/D8B3-ACBF/
rm -rf /storage/emulated/0/txtpad/
