#!/bin/bash
echo "URL"
read URL
ext=".mkv"
name="video1"
user="skuish@hotmail.com"
pass="ilove12345"
names=$name$ext
cd $HOME/Descargas/
yt-dlp -f b $URL -o $names --username $user --password $pass
ffmpeg -i $names -c:v libx264 -c:a aac "${name}.mp4"
sleep 5
rm $names
